language: bash
services: docker

env:
  - NDK=ndk EMULATOR=emulator
  - NDK=ndk
  - NULL=null

install:
  - git clone https://github.com/llog/andocker.git ~/andocker

before_script:
  - env | sort
  - cd "${NDK}${EMULATOR:+/${EMULATOR}}${NULL}"
  - image="andocker:${NDK}${EMULATOR:+-$EMULATOR}${NULL}"
  
script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
