language: bash
services: docker

env:
  - NDK=ndk EMULATOR=emulator SSHD=ssh MY=my
  - NDK=ndk
  - MINIMUM=minimum

install:
  - git clone https://github.com/llog/andocker.git ~/andocker

before_script:
  - env | sort
  - path="${NDK}${EMULATOR:+/${EMULATOR}}${MINIMUM}"
  - base="huaixiaoz/andocker"
  - cd ${path}
  - image="huaixiaoz/andocker:${NDK}${EMULATOR:+-$EMULATOR}${MINIMUM}"
  - pwd && echo ${path} && echo ${image}

script:
  - test ${SSHD} && text ${MY} && travis_retry docker build -t ${base} . || travis_retry docker build -t ${image} .
  - test ${SSHD} && travis_retry docker build -t ${base}:${SSHD} ${SSHD} || echo ${base}:"ssh build is escaped."
  - test ${MY} && travis_retry docker build --build-arg ROOT_PASSWORD=$ROOT_PASSWORD -t ${base}:${MY} ${MY} || echo ${base}:"my build is escaped."

after_script:
  - docker images
  - (test ${SSHD} && test ${MY}) && (docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push ${base} && docker push ${base}:${SSHD} && docker push ${base}:${MY}) || (docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push ${image})
