language: bash
services: docker

env:
  - NDK=ndk EMULATOR=emulator
  - NDK=ndk
  - MINIMUM=minimum

install:
  - git clone https://github.com/llog/andocker.git ~/andocker

before_script:
  - env | sort
  - path="${NDK}${EMULATOR:+/${EMULATOR}}${MINIMUM}"
  - cd ${path}
  - image="andocker:${NDK}${EMULATOR:+-$EMULATOR}${MINIMUM}"
  - pwd && echo ${path} && echo ${image}

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
